### ISSUE TITLE
File provider with dynamic configuration does not pickup changes from file watcher

### ISSUE THREAD

**Issue by FSeidinger** [traefik-contrib/traefik-snap#1]
Hey there,

I'm using the traefik snap on Ubuntu 22.04.02 LTS using the file provider configuration.

The static configuration I put into `/etc/traefik/traefik.yml` and the dynamic configuration is configured here as:

```yaml
providers:
  file:
    directory: "/etc/traefik/conf.d"
    watch: true
```
The dynamic configuration is then picked up upon start, but the file watcher does not pick up changes to the files. After changing the dynamic configuration the snap has to be restarted manually in order to pick up changes.

Is there any way that this can be changed?
